### ISSUE TITLE
ESP Version handling of _CUR _DEF commands

### ISSUE THREAD

**Issue by WheresWally** [bportaluri/WiFiEsp#10]
Hi, would it be possible to make the library use the commands that have _DEF _CUR etc only if the version of ESP attached supports them?
getFwVersion() checks the  version so can the commands use be based on what it finds?

**Comment by bportaluri** [comment]
I have decided to drop the support for 0.9.x firmware because the AT commands were not so reliable and it is quite old at the moment.
I can introduce a 'compatibility mode' in some way but I don't think it will work because the end tags have changed quite a lot and many commands will fail.
Can you try to manually remove them and tell me if it works on 0.9 ?  I think I don't have any ESP module running with the old firmware now.

**Comment by WheresWally** [comment]
I have just removed them, it is easy enough to do, but I might get sick of it eventually. haha
What is the advantage of the _CUR ?
So far, the 0.9.5 firmware has operated ok with the _CUR _DEF commands removed.

**Comment by WheresWally** [comment]
OK, I didn't think about the 'end tags', if they are different then that will cause some failures as well.
Might be time to try flashing/upgrading version again.
